apiVersion: apps/v1
kind: Deployment
metadata:
  name: srt-gw
  labels:
    app: srt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srt
  template:
    metadata:
      labels:
        app: srt
    spec:
      containers:
      - image: hidesugihara/srt
        command:
          - "/home/bin/srt-live-transmit"
          - "srt://0.0.0.0:3000?mode=listener"
          - "udp://10.0.17.27:4000"
        imagePullPolicy: IfNotPresent
        name: srt
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: pod-type
                operator: In
                values:
                - permanent-nealive
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nea-live-1
            topologyKey: "kubernetes.io/hostname"
      restartPolicy: Always

