# Default values for srt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hidesugihara/srt
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""


podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

serviceAnnotations:
  external-dns.alpha.kubernetes.io/hostname: "srt1.nl.genesis.ateme.ninja"
  external-dns.alpha.kubernetes.io/ttl: "60"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

inboundport: 3000
outboundport: 4000
outboundaddress: "nea-live-1.nl.genesis.ateme.ninja"

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: pod-type
          operator: In
          values:
          - permanent-nealive
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - nea-live-1
      topologyKey: "kubernetes.io/hostname"
