# Default values for srt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hidesugihara/srt
  pullPolicy: IfNotPresent
  # Keep the default tag
  tag: ""

# No need to modify this part, image is publicly available.
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# This tag prevents the autoscaler cluster from deleting the pod.
podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

# If you want to use external DNS, uncomment the following lines
# This will give you the possibility to use DNS name instead of IP addresses to reach you SRT GW pod.
# ExternalDNS needs to be installed and configured in the cluster.
serviceAnnotations:
  # external-dns.alpha.kubernetes.io/hostname: "srt1.nl.genesis.ateme.ninja"
  # external-dns.alpha.kubernetes.io/ttl: "60"

# Don't need to be modified
podSecurityContext: {}
  # fsGroup: 2000

# Don't need to be modified
securityContext: {}

# Port on which you will receive the stream
inboundport: 3000
# Port on which you will send the stream
outboundport: 4000
# Address or IP on which you will send the stream (NEA-Live pod)
outboundaddress: "nea-live-1.nl.genesis.ateme.ninja"

# No need to setup resources
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Autoscaling is not necessary, keep it disabled.
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

# Affinity are required to schedule SRT pods on the same node as the NEA-Live pod.
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: pod-type
          operator: In
          values:
          - permanent-nealive
  podAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - nea-live-1
      topologyKey: "kubernetes.io/hostname"
