apiVersion: v1
kind: Service
metadata:
  name: {{ include "srt.fullname" . }}
  labels:
    {{- include "srt.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.serviceAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  clusterIP: None
  ports:
    - protocol: UDP
      port: {{ .Values.inboundport }}
      targetPort: {{ .Values.inboundport }}
  selector:
    {{- include "srt.selectorLabels" . | nindent 4 }}